### ISSUE TITLE
Enhancement: support consistent hashing via StatefulSet SRV records

### ISSUE THREAD

**Issue by philandstuff** [replicate/pget#37]
```[tasklist]
### Tasks
- [x] Support configuring SRV records to follow (assumption: they are formatted like StatefulSet names ie numerically)
- [x] Split downloads in sympathy with slice size
- [x] Implement Jump consistent hashing per-slice to direct requests via cache nodes in a consistent manner (cache key should be based on hashstructure so we can extend it in future)
- [x] Handle node failure by going directly upstream
- [x] Allowlist for base URLs/origins to cache vs not cache
- [x] sand down rough edges for non-cached domains (eg not weights.replicate.delivery) @tempusfrangit
- [x] hosts-bodger functionality
- [x] benchmark with CH to ensure no regression
- [ ] https://github.com/replicate/pget/issues/92
- [ ] https://github.com/replicate/pget/issues/87
- [ ] https://github.com/replicate/pget/issues/86
- [ ] https://github.com/replicate/pget/issues/94
- [ ] https://github.com/replicate/pget/issues/98
- [ ] https://github.com/replicate/pget/pull/111
- [ ] https://github.com/replicate/pget/issues/107
```

**Comment by philandstuff** [comment]
closing this as done
